---
# common values in inventory/group_vars/all.yaml
- name: Setup primary vault cluster
  hosts: vault_primary
  become: true
  # environment:
  #   http_proxy: 'http://proxy.example.com/'
  #   https_proxy: 'http://proxy.example.com/'
  #   no_proxy: '.example.com,.example.org'
  roles:
    - role: ansible-role-vault
      vars:
        vault_ansible_group: 'vault_primary'
        vault_cluster_name: vault-primary
    - role: ansible-role-vault_extras
- name: Setup secondary vault cluster
  hosts: vault_secondary
  become: true
  # environment:
  #   http_proxy: 'http://proxy.example.com/'
  #   https_proxy: 'http://proxy.example.com/'
  #   no_proxy: '.example.com,.example.org'
  roles:
    - role: ansible-role-vault
      vars:
        vault_ansible_group: 'vault_secondary'
        vault_cluster_name: vault-secondary
    - role: ansible-role-vault_extras
